//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAndUserControl.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MasterMovieDbContext : DbContext
    {
        public MasterMovieDbContext()
            : base("name=MasterMovieDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Movie> Movies1 { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<Movie> GetAllMovies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Movie>("GetAllMovies");
        }
    
        public virtual ObjectResult<Movie> GetAllMovies(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Movie>("GetAllMovies", mergeOption);
        }
    }
}
